# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest 
    environment: stage
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
      
    - id: load-secret-gpg-key
      shell: bash
      name: Decode and save GPG Secret File from secrets
      env:
        SECRETS_GPG_KEY: ${{ secrets.ENCODED_SECRET_GPG_KEY }}
        SAMPLE_ENV: value
      run: |
        echo $SECRETS_GPG_KEY | base64 --decode > secrets

    - id: print-dir
      name: print the directory to check whether secrets-keys.gpg is generated
      run: ls -al

